name: rnd
description: Extension methods & helpers for Random, and a globally accessible instance. Ex. rnd(10), rnd.getItem(list), rnd.getBit(0.8).
repository: https://github.com/gskinner/dart_rnd
homepage: https://github.com/gskinner/dart_rnd

version: 0.1.0

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: ^1.6.7

dependencies:
  flutter:
    sdk: 'flutter'

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  uses-material-design: true
